"use strict";

document.addEventListener("DOMContentLoaded", () => {
    const dados = {
        clientes:[['Carlos Eduardo Mendes','(11) 98432-1100','2 veíc.','ativo'],['Mariana Costa Oliveira','(11) 97564-3210','1 veíc.','ativo'],['Roberto Lima Santos','(11) 96543-2109','1 veíc.','ativo'],['Ana Paula Ferreira','(11) 95432-1008','0 veíc.','inativo'],['Paulo Roberto Souza','(11) 94321-0987','1 veíc.','ativo']],
        veiculos:[['ABC-1023','Honda','Civic','2021','Prata','Flex','42.300 km','Carlos Eduardo Mendes','1 OS'],['XYZ-4056','Honda','HR-V','2023','Preto','Flex','12.800 km','Carlos Eduardo Mendes','0 OS'],['DEF-2634','Toyota','Corolla','2020','Branco','Flex','68.000 km','Mariana Costa Oliveira','1 OS'],['GHT-3145','Volkswagen','Gol','2019','Vermelho','Flex','95.000 km','Roberto Lima Santos','1 OS'],['JKL-5067','Chevrolet','Onix','2023','Cinza','Flex','8.400 km','Paulo Roberto Souza','1 OS']],
        orcamentos:[['ORC-001','Carlos Eduardo Mendes','Honda Civic · ABC-1023','10/07/2026','R$ 350,10','aprovado'],['ORC-002','Mariana Costa Oliveira','Toyota Corolla · DEF-2634','12/07/2026','R$ 209,00','pendente']],
        ordens:[['OS-2847','Carlos Eduardo Mendes','Honda Civic · ABC-1023','André S.','13/07/2026','R$ 350,10','em andamento'],['OS-2846','Mariana Costa Oliveira','Toyota Corolla · DEF-2634','Felipe R.','12/07/2026','R$ 189,00','aberta'],['OS-2845','Roberto Lima Santos','Volkswagen Gol · GHT-3145','Lucas M.','10/07/2026','R$ 192,00','concluída'],['OS-2844','Paulo Roberto Souza','Chevrolet Onix · JKL-5067','André S.','08/07/2026','R$ 84,00','concluída']],
        estoque:[['IT-001','Óleo Sintético 5W30','Lubrificantes','Litro','3','20','R$ 32,90','R$ 98,70','baixo'],['IT-002','Filtro de Óleo Universal','Filtros','Unid.','8','15','R$ 18,50','R$ 148,00','baixo'],['IT-003','Pastilha de Freio Dianteira','Freios','Par','22','10','R$ 89,00','R$ 1.958,00','ok'],['IT-004','Fluido de Freio DOT 4','Fluidos','500ml','6','12','R$ 24,00','R$ 144,00','baixo'],['IT-005','Vela de Ignição NGK','Ignição','Unid.','48','20','R$ 28,00','R$ 1.344,00','ok']],
        caixa:[['13/07/2026','OS-2845 — Velas de ignição','Serviços','OS-2845','entrada','R$ 192,00'],['12/07/2026','Compra óleo 5W30 (20 litros)','Estoque','—','saída','-R$ 658,00'],['11/07/2026','OS-2844 — Fluido de freio','Serviços','OS-2844','entrada','R$ 84,00'],['10/07/2026','Conta de energia elétrica','Fixos','—','saída','-R$ 430,00'],['09/07/2026','Aluguel da oficina — Jul/2026','Fixos','—','saída','-R$ 2.800,00'],['08/07/2026','ORC-001 — Adiantamento cliente','Orçamentos','—','entrada','R$ 300,00'],['07/07/2026','Compra filtros variados','Estoque','—','saída','-R$ 370,00'],['05/07/2026','Serviço avulso — revisão Fiat','Serviços','—','entrada','R$ 550,00']]
    };
    const titulo={dashboard:'Dashboard',clientes:'Clientes',veiculos:'Veículos',orcamentos:'Orçamentos',ordens:'Ordens de serviço',estoque:'Estoque',caixa:'Fluxo de caixa'};
    const toast=document.querySelector('[data-toast]'); const modal=document.querySelector('[data-modal]'); let filters={ordens:'todos',caixa:'todos'};
    document.querySelector('[data-date]').textContent=new Intl.DateTimeFormat('pt-BR',{weekday:'short',day:'2-digit',month:'short',year:'numeric'}).format(new Date()).replaceAll('.','');
    const status=(valor)=>`<span class="status ${valor.replace(' ','-')}">${valor}</span>`; const actions=()=>'<div class="actions"><button class="row-action" title="Editar" data-row-action="editar">⌕</button><button class="row-action delete" title="Excluir" data-row-action="excluir">⌫</button></div>';
    function renderClientes(lista=dados.clientes){document.querySelector('[data-list="clientes"]').innerHTML=lista.map(x=>`<article class="client-row"><span class="avatar">${x[0].split(' ').map(p=>p[0]).slice(0,2).join('')}</span><div class="client-main"><b>${x[0]}</b><p>${x[1]} · ${x[2]}</p></div>${status(x[3])}${actions()}</article>`).join('');document.querySelector('[data-count="clientes"]').textContent=lista.length;}
    function renderTabela(chave,lista=dados[chave]){const coluna=(v,i)=>{if(i===0)return `<strong class="id">${v}</strong>`;if(['orcamentos','ordens'].includes(chave)&&i===lista[0].length-1)return status(v);if(chave==='estoque'&&i===lista[0].length-1)return status(v);if(chave==='estoque'&&i===2)return `<span class="category">${v}</span>`;if(chave==='caixa'&&i===4)return `<span class="status ${v==='entrada'?'active':'inactive'}">${v==='entrada'?'↑ entrada':'↓ saída'}</span>`;if(chave==='caixa'&&i===5)return `<span class="amount ${v.includes('-')?'out':'in'}">${v}</span>`;return v;};document.querySelector(`[data-list="${chave}"]`).innerHTML=lista.map(x=>`<tr>${x.map(coluna).map(v=>`<td>${v}</td>`).join('')}<td>${actions()}</td></tr>`).join('');const count=document.querySelector(`[data-count="${chave}"]`);if(count)count.textContent=lista.length;}
    function renderTudo(){renderClientes();['veiculos','orcamentos','estoque'].forEach(renderTabela);renderTabela('ordens',filters.ordens==='todos'?dados.ordens:dados.ordens.filter(x=>x[6]===filters.ordens));renderTabela('caixa',filters.caixa==='todos'?dados.caixa:dados.caixa.filter(x=>x[4]===filters.caixa));}
    function trocarView(){const view=(location.hash||'#dashboard').slice(1);const atual=titulo[view]?view:'dashboard';document.querySelectorAll('[data-view-panel]').forEach(el=>el.hidden=el.dataset.viewPanel!==atual);document.querySelectorAll('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===atual));document.querySelector('[data-breadcrumb]').textContent=titulo[atual].toUpperCase();document.title=`EIXO | ${titulo[atual]}`;}
    function mensagem(texto){toast.textContent=texto;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800);}
    document.querySelectorAll('[data-search]').forEach(input=>input.addEventListener('input',()=>{const chave=input.dataset.search;const termo=input.value.toLowerCase();const lista=dados[chave].filter(x=>x.join(' ').toLowerCase().includes(termo));chave==='clientes'?renderClientes(lista):renderTabela(chave,lista);}));
    document.querySelectorAll('[data-filter-group]').forEach(grupo=>grupo.addEventListener('click',event=>{const botao=event.target.closest('[data-filter]');if(!botao)return;const chave=grupo.dataset.filterGroup;filters[chave]=botao.dataset.filter;grupo.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b===botao));renderTudo();}));
    document.querySelectorAll('[data-new]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelector('[data-modal-title]').textContent=`Novo ${btn.dataset.new}`;modal.showModal();}));
    document.addEventListener('click',event=>{const action=event.target.closest('[data-row-action]');if(!action)return;mensagem(action.dataset.rowAction==='excluir'?'Exclusão simulada: conecte esta ação ao backend.':'Edição simulada: conecte esta ação ao backend.');});
    modal.addEventListener('close',()=>{if(modal.returnValue==='default')mensagem('Rascunho salvo localmente para demonstração.');});
    const receitaMensal=[['Jan','R$ 50.000','R$ 50.000',100],['Fev','R$ 50.000','R$ 50.000',100],['Mar','R$ 55.000','R$ 45.100',91],['Abr','R$ 55.000','R$ 55.000',91],['Mai','R$ 60.000','R$ 57.000',82],['Jun','R$ 60.000','R$ 57.000',82],['Jul','R$ 66.000','R$ 64.000',70]];
    const areaGrafico=document.querySelector('[data-revenue-chart]');
    if(areaGrafico){const svg=areaGrafico.querySelector('svg'),tooltip=areaGrafico.querySelector('[data-chart-tooltip]'),guia=areaGrafico.querySelector('[data-chart-guide]'),ponto=areaGrafico.querySelector('[data-chart-dot]');const esconder=()=>{tooltip.hidden=true;guia.hidden=true;ponto.hidden=true;};svg.addEventListener('pointermove',evento=>{const box=svg.getBoundingClientRect();const porcentagem=Math.max(0,Math.min(1,(evento.clientX-box.left)/box.width));const indice=Math.round(porcentagem*(receitaMensal.length-1));const [mes,meta,valor,y]=receitaMensal[indice];const x=(820/(receitaMensal.length-1))*indice;tooltip.querySelector('b').textContent=mes;tooltip.querySelector('.meta').textContent=`Meta ${meta}`;tooltip.querySelector('strong').textContent=valor;tooltip.style.left=`${(x/820)*100}%`;tooltip.style.top=`${(y/175)*100}%`;tooltip.hidden=false;guia.setAttribute('x1',x);guia.setAttribute('x2',x);guia.hidden=false;ponto.setAttribute('cx',x);ponto.setAttribute('cy',y);ponto.hidden=false;});svg.addEventListener('pointerleave',esconder);svg.addEventListener('blur',esconder);}
    window.addEventListener('hashchange',trocarView); renderTudo(); trocarView();
});
